/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 bergenia_flower.glb 
Author: Lassi Kaukonen (https://sketchfab.com/thesidekick)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bergenia-flower-a0f3d23779a2471a861e67249dd95fae
Title: Bergenia Flower
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import scene from "/Users/guranshvir/Documents/Rose-3D-Project/rose_vite_3d/react-3d-model/src/assets/Bergenia_Flower/bergenia_flower.glb"

export default function Model(props) {
  const { nodes, materials } = useGLTF(scene)
  return (
    <group {...props} dispose={null} scale={0.08}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Bergenia_flower} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Bergenia_flower} />
      </group>
    </group>
  )
}

useGLTF.preload(scene)
