/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 chinese_rose.glb 
Author: sujirour (https://sketchfab.com/sujirour)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chinese-rose-eaee5c918ab74563867f445569eb65bc
Title: Chinese Rose
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import scene from "/Users/guranshvir/Documents/Rose-3D-Project/rose_vite_3d/react-3d-model/src/assets/Rose_Chinese/chinese_rose.glb"

export default function Model(props) {
  const { nodes, materials } = useGLTF(scene)
  return (
    <group {...props} dispose={null} scale={0.2}>
      <mesh geometry={nodes.chinese_rose_small_chinese_rose_mat_0.geometry} material={materials.chinese_rose_mat} position={[-0.197, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.chinese_rose_chinese_rose_mat_0.geometry} material={materials.chinese_rose_mat} position={[0.2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload(scene)
