/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 dry_flower.glb 
Author: Second Studio (https://sketchfab.com/kayaaku)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dry-flower-ff0005d6eb4d4077bd08b8992299c45c
Title: Dry flower
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import scene from "/Users/guranshvir/Documents/Rose-3D-Project/rose_vite_3d/react-3d-model/src/assets/Dry_flower_New/compressed.glb"

export default function Model(props) {
  const { nodes, materials } = useGLTF(scene)
  return (
    <group {...props} dispose={null} scale={2}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.draifrawer_u1_v1} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.draifrawer_u1_v1} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.draifrawer_u1_v1} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.draifrawer_u1_v1} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.draifrawer_u1_v1} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.draifrawer_u1_v1} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.draifrawer_u1_v1} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.draifrawer_u1_v1} />
      </group>
    </group>
  )
}

useGLTF.preload(scene)
