/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 dry_flower.glb 
Author: Second Studio (https://sketchfab.com/kayaaku)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dry-flower-d565e8b73f35430a882789ed9c434299
Title: Dry flower
*/

import React, { useRef } from 'react'
import { useGLTF, OrbitControls } from '@react-three/drei'
import flowerscene from "/Users/guranshvir/Documents/Rose-3D-Project/rose_vite_3d/react-3d-model/src/assets/DryFlower/compressed.glb"

export default function Model(props) {
  const { nodes, materials } = useGLTF(flowerscene)
  return (
    <group {...props} dispose={null} scale={7}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.ddryflower_u1_v1} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload(flowerscene)
