/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 glowing_flower-transformed.glb 
Author: Mila (Liudmyla) Andrushchenko (https://sketchfab.com/mila3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/glowing-flower-f25f5af218694950a1b9a0452046caea
Title: Glowing Flower
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import flowerscene from "/Users/guranshvir/Documents/Rose-3D-Project/rose_vite_3d/react-3d-model/src/assets/AnimatedFlower/glowing_flower-transformed.glb"

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(flowerscene)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene" scale={0.1}>
        <group name="RootNode" scale={0.01}>
          <group name="Empty" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group name="Sphere003" position={[0.671, -0.648, 3.301]} rotation={[0, 0, -1.895]} scale={1.422}>
            </group>
          </group>
        </group >
          <mesh name="Plane_Material004_0" geometry={nodes.Plane_Material004_0.geometry} material={materials['Material.004']} rotation={[-1.687, 0.097, -0.032]} />
          <mesh name="Plane_Material005_0" geometry={nodes.Plane_Material005_0.geometry} material={materials['Material.005']} rotation={[-1.687, 0.097, -0.032]} />
          <mesh name="Plane001_Material003_0" geometry={nodes.Plane001_Material003_0.geometry} material={materials['Material.003']} position={[0, -0.205, 0]} rotation={[-1.671, 0.019, -0.33]} scale={1.489} />
          <mesh name="Plane002_Material002_0" geometry={nodes.Plane002_Material002_0.geometry} material={materials['Material.002']} position={[0, -0.292, 0]} rotation={[-1.869, -0.197, 0.618]} scale={[1.016, 1.016, 1.902]} />
          <mesh name="Vert001_Material001_0" geometry={nodes.Vert001_Material001_0.geometry} material={materials['Material.001']} rotation={[-1.622, -0.078, -2.98]} />
        </group>
    </group>
  )
}

useGLTF.preload(flowerscene)
