/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 margarita_flower.glb 
Author: Maf'j Alvarez (https://sketchfab.com/blujay)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/margarita-flower-58ce34c65642408cb92eab784af2bd6c
Title: Margarita flower
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import flowerscene from "/Users/guranshvir/Documents/Rose-3D-Project/rose_vite_3d/react-3d-model/src/assets/MargaritaFlower/margarita_flower.glb"

export default function Model(props) {
  const { nodes, materials } = useGLTF(flowerscene)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.25}> 
        <mesh geometry={nodes.margarita_flower_green_0.geometry} material={materials.green} />
        <mesh geometry={nodes.margarita_flower_white_0.geometry} material={materials.white} />
        <mesh geometry={nodes.margarita_flower_yellow_0.geometry} material={materials.yellow} />
      </group>
    </group>
  )
}

useGLTF.preload(flowerscene)
