/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 piano_rose_new.glb 
Author: heyyodd (https://sketchfab.com/heyyodd)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/piano-rose-new-73834d42336e4705a20fb36cc89e4e72
Title: piano rose new
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import scene from "/Users/guranshvir/Documents/Rose-3D-Project/rose_vite_3d/react-3d-model/src/assets/Rose/piano_rose_new.glb"

export default function Model(props) {
  const { nodes, materials } = useGLTF(scene)
  return (
    <group {...props} dispose={null} scale={1.3}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.081}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.leaf_001_leaf_010_004001_leaf_0.geometry} material={materials.leaf} position={[-63.884, 377.63, 13.813]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes.leaf_002_leaf_011_004001_leaf_0.geometry} material={materials.leaf} position={[-26.384, 366.365, 3.08]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes.leaf_003_leaf_012_004001_leaf_0.geometry} material={materials.leaf} position={[-25.108, 382.028, 54.397]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes.leaf_004_leaf_013_004001_leaf_0.geometry} material={materials.leaf} position={[97.17, 442.293, -46.495]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes.leaf_005_leaf_014_004001_leaf_0.geometry} material={materials.leaf} position={[80.584, 433.898, -23.677]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes.leaf_006_leaf_015_004001_leaf_0.geometry} material={materials.leaf} position={[57.997, 444.472, -51.043]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_001_5p_petal_001_006_004001_(5)1-1max_0'].geometry} material={materials['51-1max']} position={[39.699, 552.929, 8.615]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_001_petal_165_004001_2-1max_0'].geometry} material={materials['2-1max']} position={[30.877, 556.692, 14.113]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_002_5p_petal_003_006_004001_(5)1-1max_0'].geometry} material={materials['51-1max']} position={[39.455, 549.336, 7.325]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_002_petal_124_004001_2-1max_0'].geometry} material={materials['2-1max']} position={[30.948, 560.007, 6.088]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_003_5p_petal_005_006_004001_(5)1-1max_0'].geometry} material={materials['51-1max']} position={[39.204, 544.602, 8.164]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_003_petal_143_004001_2-1max_0'].geometry} material={materials['2-1max']} position={[40.793, 560.624, 7.563]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_004_petal_160_004001_2-1max_0'].geometry} material={materials['2-1max']} position={[40.997, 549.651, 18.159]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_005_petal_158_004001_2-1max_0'].geometry} material={materials['2-1max']} position={[29.46, 558.232, 17.354]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_006_petal_121_004001_2-1max_0'].geometry} material={materials['2-1max']} position={[24.699, 558.615, 9.838]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_007_petal_139_004001_2-1max_0'].geometry} material={materials['2-1max']} position={[26.434, 557.739, 2.698]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_008_petal_138_004001_2-1max_0'].geometry} material={materials['2-1max']} position={[45.394, 559.161, 7.638]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_009_petal_125_004001_2-1max_0'].geometry} material={materials['2-1max']} position={[44.13, 557.141, 20.062]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_010_petal_142_004001_2-1max_0'].geometry} material={materials['2-1max']} position={[24.142, 557.076, 9.745]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_011_petal_140_004001_4-1max_0'].geometry} material={materials['4-1max']} position={[22.875, 558.089, 1.172]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_012_petal_147_004001_2-1max_0'].geometry} material={materials['2-1max']} position={[38.261, 557.04, -1.955]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_013_petal_126_004001_2-1max_0'].geometry} material={materials['2-1max']} position={[51.634, 558.202, 13.143]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_014_petal_171_004001_2-1max_0'].geometry} material={materials['2-1max']} position={[28.749, 558.045, 22.476]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_015_petal_145_004001_2-1max_0'].geometry} material={materials['2-1max']} position={[21.448, 556.363, 10.671]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_016_petal_148_004001_4-1max_0'].geometry} material={materials['4-1max']} position={[37.781, 557.247, -4.819]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_017_petal_149_004001_2-1max_0'].geometry} material={materials['2-1max']} position={[46.849, 559.623, -1.078]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_018_petal_122_004001_2-1max_0'].geometry} material={materials['2-1max']} position={[49.559, 557.975, 6.872]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_019_petal_127_004001_4-1max_0'].geometry} material={materials['4-1max']} position={[54.401, 557.683, 14.618]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_020_petal_170_004001_4-1max_0'].geometry} material={materials['4-1max']} position={[47.98, 559.49, 22.53]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_021_petal_120_004001_4-1max_0'].geometry} material={materials['4-1max']} position={[31.121, 556.535, 29.333]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_022_petal_146_004001_4-1max_0'].geometry} material={materials['4-1max']} position={[24.632, 556.999, 24.397]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_023_petal_162_004001_4-1max_0'].geometry} material={materials['4-1max']} position={[15.797, 557.209, 13.185]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_024_petal_164_004001_4-1max_0'].geometry} material={materials['4-1max']} position={[19.928, 556.678, -0.321]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_025_petal_150_004001_4-1max_0'].geometry} material={materials['4-1max']} position={[34.173, 557.106, -6.9]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_026_petal_135_004001_4-1max_0'].geometry} material={materials['4-1max']} position={[49.93, 559.638, -4.96]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_027_petal_129_004001_4-1max_0'].geometry} material={materials['4-1max']} position={[52.695, 558.654, 3.717]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_028_petal_128_004001_4-1max_0'].geometry} material={materials['4-1max']} position={[57.163, 557.529, 14.451]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_029_petal_155_004001_4-1max_0'].geometry} material={materials['4-1max']} position={[48.887, 558.78, 26.073]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_030_petal_152_004001_4-1max_0'].geometry} material={materials['4-1max']} position={[14.24, 556.789, 13.034]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_031_petal_136_004001_4-1max_0'].geometry} material={materials['4-1max']} position={[52.357, 560.321, -9.351]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_032_petal_153_004001_4-1max_0'].geometry} material={materials['4-1max']} position={[51.821, 559.652, -10.06]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_033_petal_157_004001_4-1max_0'].geometry} material={materials['4-1max']} position={[58.281, 561.145, 0.907]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_034_petal_166_004001_6-1max_0'].geometry} material={materials['6-1max']} position={[48.863, 539.298, 29.754]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_035_petal_154_004001_6-1max_0'].geometry} material={materials['6-1max']} position={[54.259, 542.926, -15.578]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_036_petal_163_004001_6-1max_0'].geometry} material={materials['6-1max']} position={[12.27, 539.826, 8.388]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_037_petal_174_004001_6-1max_0'].geometry} material={materials['6-1max']} position={[65, 538.828, 6.91]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_038_petal_167_004001_6-1max_0'].geometry} material={materials['6-1max']} position={[27.701, 535.959, -15.15]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_039_petal_168_004001_6-1max_0'].geometry} material={materials['6-1max']} position={[25.486, 534.319, 30.141]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_040_petal_169_004001_6-1max_0'].geometry} material={materials['6-1max']} position={[51.859, 533.287, -17.419]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_041_petal_159_004001_7-1max_0'].geometry} material={materials['7-1max']} position={[10.472, 524.742, 3.675]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_042_petal_173_004001_6-1max_0'].geometry} material={materials['6-1max']} position={[53.37, 530.692, 30.651]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_043_petal_175_004001_7-1max_0'].geometry} material={materials['7-1max']} position={[58.63, 518.482, -2.747]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['petal_044_petal_176_004001_7-1max_ending_0'].geometry} material={materials['7-1max_ending']} position={[39.198, 509.813, 28.056]} rotation={[-Math.PI / 2, 0, 0]} scale={[13797.519, 13797.519, 13797.518]} />
          <mesh geometry={nodes.stem_001_stem_006_004001_stem_0.geometry} material={materials.stem} position={[39.749, 405.106, 4.682]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['stem_002_1_stem_007_004001_stem-S_0'].geometry} material={materials['stem-S']} position={[11.026, 365.228, 25.45]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes['stem_002_2_stem_008_004001_stem-S_0'].geometry} material={materials['stem-S']} position={[52.112, 427.597, -21.822]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes.thorn1_thorn_0.geometry} material={materials.thorn} position={[44.555, 467.79, 3.615]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes.thorn2_thorn_0.geometry} material={materials.thorn} position={[43.72, 454.961, -3.188]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes.thorn3_thorn_0.geometry} material={materials.thorn} position={[39.834, 319.043, 13.858]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes.thorn4_thorn_0.geometry} material={materials.thorn} position={[45.449, 369.235, 0.94]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
          <mesh geometry={nodes.thorn5_thorn_0.geometry} material={materials.thorn} position={[40.079, 421.379, -0.457]} rotation={[-Math.PI / 2, 0, 0]} scale={[15000, 15000, 14999.998]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(scene)
