/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 PurpleGermaniumflOWER.glb 
Author: MyVisoin (https://sketchfab.com/TemurG)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/geranium-flower-e2b49bd91dcd4bc3aecbd65160a38756
Title: Geranium flower
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import flowerscene from "/Users/guranshvir/Documents/Rose-3D-Project/rose_vite_3d/react-3d-model/src/assets/GermaniumFlower/PurpleGermaniumflOWER.glb"

export default function Model(props) {
  const { nodes, materials } = useGLTF(flowerscene)
  return (
    <group {...props} dispose={null}>
      <group rotation={[0.142, -0.002, -0.202]} scale={0.0042}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Geranium} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Geranium} />
      </group>
    </group>
  )
}

useGLTF.preload(flowerscene)
